version: "3"
services:
    rabbitmq:
        image: rabbitmq:3-management
        restart: on-failure
        ports:
            - "15672:15672"
            - "5672:5672"
        logging:
            options:
                max-size: "10m"
                max-file: "10"

    config:
        image: alkonoriev/distributed-lab-config
        restart: on-failure
        ports:
            - "8888:8888"
        network_mode: "host"

    registry:
        image: alkonoriev/distributed-lab-registry:latest
        restart: on-failure
        ports:
            - "8761:8761"
        network_mode: "host"

    product-service:
        image: alkonoriev/distributed-lab-product-service
        restart: on-failure
        network_mode: "host"
